services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - restoration-net

  supabase-auth:
    image: supabase/gotrue:v2.43.0
    environment:
      GOTRUE_JWT_SECRET: ${JWT_SECRET:?err_no_jwt_secret}
      GOTRUE_DB_DRIVER: postgres
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9999:9999"
    networks:
      - restoration-net

  fastapi:
    build:
      context: .
      dockerfile: api/Dockerfile
      target: ${BUILD_TARGET:-development}
      args:
        PYTHON_VERSION: "3.11"
      # BuildKit configuration
      x-bake:
        platforms: ["linux/amd64"]
        cache-from: 
          - type=local,src=./.buildcache
        cache-to:
          - type=local,dest=./.buildcache,mode=max
    image: localhost/restoration-intel-api:${TAG:-latest}
    ports:
      - "8000:8000"
    volumes:
      # Hot reload for development
      - ./api/py:/app/py:ro
      - ./api/__init__.py:/app/__init__.py:ro
      # Cache entire Python installation
      - python_packages:/usr/local
    depends_on:
      postgres:
        condition: service_healthy
      supabase-auth:
        condition: service_started
    environment:
      SUPABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:?err_no_anon_key}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY:?err_no_service_role_key}
      # Enable hot reload for development
      UVICORN_RELOAD: ${UVICORN_RELOAD:-true}
    networks:
      - restoration-net
    # Enable health checks
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nextjs:
    build:
      # Simplified context and dockerfile path for Windows compatibility
      context: ./next-app
      dockerfile: ./Dockerfile
    image: localhost/restoration-intel-frontend:${TAG:-latest}
    ports:
      - "3000:3000"
    depends_on:
      fastapi:
        condition: service_healthy
      postgres:
        condition: service_healthy
      supabase-auth:
        condition: service_started
    environment:
      NEXT_PUBLIC_SUPABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:?err_no_anon_key}
      PYTHON_API_URL: http://fastapi:8000
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./next-app:/app
      - node_modules:/app/node_modules
    networks:
      - restoration-net

networks:
  restoration-net:
    driver: bridge

volumes:
  postgres_data:
  node_modules:
  python_packages:
