"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('collections', sa.Column('confidence_percentage', sa.FLOAT(), nullable=True, default=85))
    # ### end Alembic commands ###

def downgrade():
    op.drop_column('collections', 'updated_at')
    op.drop_column('collections', 'confidence_percentage')